repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-yaml
    -   id: check-json
    -   id: pretty-format-json
        args: [--autofix]
-   repo: https://github.com/ansible/ansible-lint
    rev: v24.9.2
    hooks:
    -   id: ansible-lint
        files: packer/.*\.(yaml|yml)$
